name: Scala CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build with Java ${{ matrix.java }} and ${{ matrix.distribution }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java: [17, 21]
        os: [ubuntu-latest, macos-latest]
        distribution: [temurin, zulu, corretto]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: sbt

      - name: Set up sbt
        uses: sbt/setup-sbt@v1.11

      - name: Build and Test
        run: sbt clean compile test
