name: Scala CI Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Java ${{ matrix.java }} and ${{ matrix.distribution }} 
    #name: Build with Java ${{ matrix.java }}, Scala ${{ matrix.scala }}, and ${{ matrix.distribution }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: ['17', '21']
        #scala: ['3.3.3','3.3.6']
        os: [ubuntu-latest, macos-latest]
        distribution: ['adopt', 'temurin','zulu', 'corretto', 'microsoft']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4.7.1
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'sbt'
          cache-dependency-path: | # optional
            sub-project/build.sbt
            sub-project/project/build.properties

      - name: Set up Sbt    
        uses: sbt/setup-sbt@v1.11
        # with:
        # sbt-runner-version: 1.11.2
      - name: Cache sbt and dependencies
        uses: coursier/cache-action@v6.4.7
      - name: Build with SBT
        shell: bash
        run: sbt compile
